;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
	backward-char
	beginning-of-line
	forward-char
	mc/keyboard-quit
	move-end-of-line
	next-line
	previous-line
	self-insert-command
	xref-find-definitions
	))

(setq mc/cmds-to-run-once
      '(
	backward-delete-char-untabify
	boon-c-god
	delete-backward-char
	hydra-change-mode/body
	hydra-change-mode/lambda-d-and-exit
	undefined
	))
